project:
  type: website
  output-dir: docs

website:
  title: "Noob’s Site Diary"
  navbar:
    right:
      - text: "About"
        icon: person
        href: about.qmd
      - text: "Github"
        icon: github
        href: https://github.com/Acrea-QwQ
format:
  html:
    theme: yeti
    css: styles.css
bibliography: reference.bib


